<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\House;
use App\Entity\HouseImage;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Filesystem\Filesystem;


class ImagesController extends AbstractController
{
    /**
     * @Route("/backend/alterar-casa/imagens/{slug}", name="manage_images")
     */
    public function manageImages($slug)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $house = $this->getDoctrine()->getRepository(House::class)->findOneBy(array(
            'slug'=>$slug)
        );

        $images = $this->getDoctrine()->getRepository(HouseImage::class)->findBy(array(
            'house'=>$house
        ));

        return $this->render('images/index.html.twig', [
            'images' => $images, 'house'=>$house
        ]);
    }

    /**
     * @Route("/backend/image-form/{slug}", name="image_form")
     *
     */
    public function inputImage(Request $request, $slug){

        $house = $this->getDoctrine()->getRepository(House::class)->findOneBy(array(
                'slug'=>$slug)
        );

        $houseImage = new HouseImage();
        $imageform = $this->createFormBuilder($houseImage)
            ->add('image', FileType::class, array('mapped'=> false))
            ->add('save', SubmitType::class, array('label' => 'Adicionar Imagem'))
            ->getForm();

        $imageform->handleRequest($request);

        echo $houseImage->getName();

        if($imageform->isSubmitted() && $imageform->isSubmitted()){

            $file = $imageform->get('image')->getData();

            $fileDir = $this->getParameter('houseimages_directory') . '/' . $house->getId();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move($fileDir,$fileName);

            $houseImage->setName($fileName);

            $house->addImage($houseImage);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($houseImage);
            $entityManager->flush();

            $this->addFlash('success', 'Imagem inserida com sucesso');

            return $this->redirectToRoute('manage_images', array('slug'=>$house->getSlug()));
        }

        return $this->render('images/addImage.html.twig', array(
            'form' => $imageform->createView()
        ));
    }

    /**
     * @Route("/backend/delete-image/{image}", name="delete_image")
     */
    public function deleteImage($image){
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $entityManager = $this->getDoctrine()->getManager();
        $houseImage = $entityManager->getRepository(HouseImage::class)->findOneBy(array('name' => $image));

        $fileDir = $this->getParameter('housemainimage_directory');
        if(file_exists("$fileDir/$image")){
            $fileSystem = new Filesystem();
            $fileName2 = $fileDir . '/' . $image;
            $fileSystem->remove($fileName2);
        }

        $entityManager->remove($houseImage);
        $entityManager->flush();

        $this->addFlash('success', 'Imagem removida com sucesso');

        return $this->redirectToRoute('manage_images',array("slug"=>$houseImage->getHouse()->getSlug()));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
