index:
    path: /
    controller: App\Controller\IndexController::index

houseSearch:
    path: /{type}/cidades/{slug}
    controller: App\Controller\CityController::house

house:
    path: /{type}/cidades/{slug}/{housename}
    controller: App\Controller\HouseController::index

backend:
    path: /backend
    controller: App\Controller\BackendController::index

app_logout:
    path: /logout

new_city:
  path: /backend/adicionar-cidade
  controller: App\Controller\BackendController::newCity

change_city:
  path: /backend/alterar-cidade/{slug}
  controller: App\Controller\BackendController::changeCity

new_house:
  path: /backend/adicionar-casa
  controller: App\Controller\BackendController:newHouse

delete_city:
  path: /backend/apagar-cidade/{id}
  controller: App\Controller\BackendController:deleteCity

change_house_city:
  path: /backend/escolher-casa/{slug}/
  controller: App\Controller\BackendController:showHousesCity

change_house:
  path: /backend/alterar-casa/{city}/{house}
  controller: App\Controller\BackendController:changeHouse