index:
    path: /
    controller: App\Controller\IndexController::index

houseSearch:
    path: /{type}/cidades/{slug}
    controller: App\Controller\CityController::house

house:
    path: /{type}/cidades/{slug}/{housename}
    controller: App\Controller\HouseController::index

backend:
    path: /backend
    controller: App\Controller\BackendController::index

app_logout:
    path: /logout

new_city:
  path: /backend/adicionar-cidade
  controller: App\Controller\BackendController::newCity

change_city:
  path: /backend/alterar-cidade/{slug}
  controller: App\Controller\BackendController::changeCity

new_house:
  path: /backend/adicionar-casa
  controller: App\Controller\BackendController:newHouse

delete_city:
  path: /backend/apagar-cidade/{id}
  controller: App\Controller\BackendController:deleteCity

change_house_city:
  path: /backend/escolher-casa/{slug}
  controller: App\Controller\BackendController:showHousesCity

delete_house:
  path: /backend/alterar-casa/apagar/{slug}
  controller: App\Controller\BackendController::deleteHouse

manage_images:
  path: /backend/alterar-casa/imagens/{slug}
  controller: App\Controller\ImagesController::manageImages

image_form:
  path: /backend/image-form/{slug}
  controller: App\Controller\ImagesController::inputImage

delete_image:
  path: /backend/delete-image/{image}
  controller: App\Controller\ImagesController:deleteImage

change_house:
  path: /backend/alterar-casa/{city}/{house}
  controller: App\Controller\BackendController:changeHouse